if (!localStorage.getItem("allRecipes")) {
    const initialRecipes = [
        {
            id: 1,
            coverSrc: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
            title: "Turmeric Roasted Cauliflower Salad",
            description: "Low in calories and packed with punchy flavor from turmeric and roasted veggies.",
            author: "Joana Jardim",
            avatar: "https://randomuser.me/api/portraits/women/1.jpg",
            totalTime: "00:40",
            preparationTime: "00:40",
            finalWeight: "978.8 grams",
            portions: 4,
            nutrient: { energy: 143, fat: 6, carb: 18, protein: 5, fiber: 4 }, micronutrients: [
                { name: "Sodium", value: 1418, mass: "mg" },
                { name: "Calcium", value: 110, mass: "mg" }
            ],
            ingredients: [
                "1 cup chopped cauliflower (107g)",
                "1 tsp turmeric powder (3g)",
                "1 tbsp olive oil (14g)",
                "100g brown rice",
                "150g edamame",
                "1 lemon (212g)",
                "1 cup sliced cucumber (104g)"
            ],
            cookingMethods: [
                { id: 1, content: "Roast cauliflower with turmeric at 200°C for 25 min." },
                { id: 2, content: "Boil brown rice and edamame, mix with cucumber and lemon." },
                { id: 3, content: "Whisk dressing, combine all, serve with herbs and cashews." }
            ],
            categories: ["Vegetarian", "Low Calorie"],
            like: 37
        },
        {
            id: 2,
            coverSrc: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
            title: "Grilled Chicken Bowl",
            description: "A high-protein grilled chicken meal with quinoa and avocado.",
            author: "Alex Tran",
            avatar: "https://randomuser.me/api/portraits/men/2.jpg",
            totalTime: "00:30",
            preparationTime: "00:15",
            finalWeight: "650 grams",
            portions: 2,
            nutrient: { energy: 290, fat: 8, carb: 22, protein: 32, fiber: 5 }, micronutrients: [
                { name: "Iron", value: 2.5, mass: "mg" },
                { name: "Potassium", value: 800, mass: "mg" }
            ],
            ingredients: [
                "200g grilled chicken breast",
                "100g cooked quinoa",
                "1/2 avocado",
                "Mixed greens"
            ],
            cookingMethods: [
                { id: 1, content: "Grill chicken with olive oil." },
                { id: 2, content: "Cook quinoa and let cool." },
                { id: 3, content: "Assemble bowl with all ingredients." }
            ],
            categories: ["High Protein", "Meal Prep"],
            like: 52
        },
        {
            id: 3,
            coverSrc: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
            title: "Vegan Lentil Soup",
            description: "Warm, hearty lentil soup full of plant-based protein.",
            author: "Sara Smith",
            avatar: "https://randomuser.me/api/portraits/women/3.jpg",
            totalTime: "01:00",
            preparationTime: "00:15",
            finalWeight: "1000 grams",
            portions: 4,
            nutrient: { energy: 180, fat: 3, carb: 28, protein: 12, fiber: 10 }, micronutrients: [
                { name: "Fiber", value: 10, mass: "g" },
                { name: "Sodium", value: 950, mass: "mg" }
            ],
            ingredients: [
                "1 cup dried lentils",
                "1 carrot",
                "1 onion",
                "2 cloves garlic",
                "1L vegetable broth"
            ],
            cookingMethods: [
                { id: 1, content: "Sauté vegetables with olive oil." },
                { id: 2, content: "Add lentils and broth, simmer for 40 min." }
            ],
            categories: ["Vegan", "Soup"],
            like: 31
        },
        {
            id: 4,
            coverSrc: "https://images.unsplash.com/photo-1525351484163-7529414344d8",
            title: "Avocado Toast",
            description: "Quick and healthy breakfast packed with good fats.",
            author: "Lily Wang",
            avatar: "https://randomuser.me/api/portraits/women/4.jpg",
            totalTime: "00:10",
            preparationTime: "00:10",
            finalWeight: "300 grams",
            portions: 1,
            nutrient: { energy: 210, fat: 11, carb: 20, protein: 6, fiber: 4 }, micronutrients: [
                { name: "Vitamin C", value: 10, mass: "mg" },
                { name: "Magnesium", value: 40, mass: "mg" }
            ],
            ingredients: [
                "2 slices whole grain bread",
                "1 avocado",
                "Lemon juice",
                "Chili flakes"
            ],
            cookingMethods: [
                { id: 1, content: "Toast bread." },
                { id: 2, content: "Mash avocado with lemon and spices." },
                { id: 3, content: "Spread and serve." }
            ],
            categories: ["Vegetarian", "Quick"],
            like: 45
        },
        {
            id: 5,
            coverSrc: "https://images.unsplash.com/photo-1613145993558-5bc7c6af5b13",
            title: "Tofu Stir Fry",
            description: "Protein-packed tofu with colorful veggies in soy-ginger sauce.",
            author: "Tom Lee",
            avatar: "https://randomuser.me/api/portraits/men/5.jpg",
            totalTime: "00:25",
            preparationTime: "00:10",
            finalWeight: "600 grams",
            portions: 2,
            nutrient: { energy: 240, fat: 10, carb: 15, protein: 18, fiber: 6 }, micronutrients: [
                { name: "Calcium", value: 200, mass: "mg" },
                { name: "Zinc", value: 2.1, mass: "mg" }
            ],
            ingredients: [
                "200g firm tofu",
                "1 bell pepper",
                "1 zucchini",
                "Soy sauce, ginger"
            ],
            cookingMethods: [
                { id: 1, content: "Sauté tofu until golden." },
                { id: 2, content: "Add vegetables and stir-fry." },
                { id: 3, content: "Mix in sauce and serve hot." }
            ],
            categories: ["Vegan", "Asian"],
            like: 40
        }
    ];

    localStorage.setItem("allRecipes", JSON.stringify(initialRecipes));
    window.allRecipes = initialRecipes;
    console.log("✅ Đã tạo 5 recipe mẫu vào localStorage.");
} else {
    window.allRecipes = JSON.parse(localStorage.getItem("allRecipes"));
}


const ingredients = [
    {
        id: 1,
        name: "Broccoli",
        macronutrients: {
            energy: 34,
            carbohydrate: 6.6,
            fat: 0.4,
            protein: 2.8
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 2.6,
            sodium: 33.0,
            water: 89.3,
            vitaminA: 623.0,
            vitaminB6: 0.2,
            vitaminB12: 0.0,
            vitaminC: 89.2,
            vitaminD: 0.0,
            vitaminE: 0.8,
            vitaminK: 101.6,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 1.7,
            calcium: 47.0,
            iron: 0.7,
            magnesium: 21.0,
            phosphorus: 66.0,
            potassium: 316.0,
            zinc: 0.4,
            copper: 0.05,
            fluoride: null,
            manganese: 0.2,
            selenium: 2.5,
            thiamin: 0.07,
            riboflavin: 0.12,
            niacin: 0.64,
            pantothenicAcid: 0.5,
            folateTotal: 63.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.04,
            fattyAcidsMonounsaturated: 0.01,
            fattyAcidsPolyunsaturated: 0.04,
            chloride: 55.0
        }
    },
    {
        id: 2,
        name: "Chicken Breast",
        macronutrients: {
            energy: 165,
            carbohydrate: 0.0,
            fat: 3.6,
            protein: 31.0
        },
        micronutrients: {
            cholesterol: 85.0,
            fiber: null,
            sodium: 74.0,
            water: 65.3,
            vitaminA: 13.0,
            vitaminB6: 0.6,
            vitaminB12: 0.3,
            vitaminC: 0.0,
            vitaminD: 0.1,
            vitaminE: 0.27,
            vitaminK: 0.3,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.0,
            calcium: 15.0,
            iron: 1.0,
            magnesium: 29.0,
            phosphorus: 220.0,
            potassium: 256.0,
            zinc: 1.0,
            copper: 0.04,
            fluoride: null,
            manganese: 0.02,
            selenium: 27.6,
            thiamin: 0.07,
            riboflavin: 0.1,
            niacin: 13.7,
            pantothenicAcid: 1.0,
            folateTotal: 4.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 1.0,
            fattyAcidsMonounsaturated: 1.2,
            fattyAcidsPolyunsaturated: 0.8,
            chloride: 60.0
        }
    },
    {
        id: 3,
        name: "White Rice (cooked)",
        macronutrients: {
            energy: 130,
            carbohydrate: 28.0,
            fat: 0.3,
            protein: 2.7
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 0.4,
            sodium: 1.0,
            water: 68.4,
            vitaminA: null,
            vitaminB6: 0.1,
            vitaminB12: 0.0,
            vitaminC: 0.0,
            vitaminD: 0.0,
            vitaminE: 0.1,
            vitaminK: 0.1,
            starch: 26.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.1,
            calcium: 10.0,
            iron: 1.2,
            magnesium: 12.0,
            phosphorus: 43.0,
            potassium: 35.0,
            zinc: 0.4,
            copper: 0.07,
            fluoride: null,
            manganese: 0.5,
            selenium: 7.5,
            thiamin: 0.02,
            riboflavin: 0.02,
            niacin: 0.4,
            pantothenicAcid: 0.4,
            folateTotal: 58.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.1,
            fattyAcidsMonounsaturated: 0.1,
            fattyAcidsPolyunsaturated: 0.1,
            chloride: 1.0
        }
    }, {
        id: 4,
        name: "Banana",
        macronutrients: {
            energy: 89,
            carbohydrate: 22.8,
            fat: 0.3,
            protein: 1.1
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 2.6,
            sodium: 1.0,
            water: 74.9,
            vitaminA: 64.0,
            vitaminB6: 0.4,
            vitaminB12: 0.0,
            vitaminC: 8.7,
            vitaminD: 0.0,
            vitaminE: 0.1,
            vitaminK: 0.5,
            starch: 5.4,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 12.2,
            calcium: 5.0,
            iron: 0.3,
            magnesium: 27.0,
            phosphorus: 22.0,
            potassium: 358.0,
            zinc: 0.2,
            copper: 0.08,
            fluoride: null,
            manganese: 0.3,
            selenium: 1.0,
            thiamin: 0.03,
            riboflavin: 0.07,
            niacin: 0.7,
            pantothenicAcid: 0.3,
            folateTotal: 20.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.1,
            fattyAcidsMonounsaturated: 0.03,
            fattyAcidsPolyunsaturated: 0.07,
            chloride: 3.0
        }
    },
    {
        id: 5,
        name: "Egg (boiled)",
        macronutrients: {
            energy: 155,
            carbohydrate: 1.1,
            fat: 11.0,
            protein: 13.0
        },
        micronutrients: {
            cholesterol: 373.0,
            fiber: null,
            sodium: 124.0,
            water: 75.0,
            vitaminA: 160.0,
            vitaminB6: 0.1,
            vitaminB12: 1.1,
            vitaminC: 0.0,
            vitaminD: 2.0,
            vitaminE: 1.0,
            vitaminK: 0.3,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 1.1,
            calcium: 50.0,
            iron: 1.2,
            magnesium: 10.0,
            phosphorus: 86.0,
            potassium: 126.0,
            zinc: 1.0,
            copper: 0.06,
            fluoride: null,
            manganese: 0.03,
            selenium: 30.8,
            thiamin: 0.03,
            riboflavin: 0.5,
            niacin: 0.1,
            pantothenicAcid: 1.4,
            folateTotal: 47.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 3.3,
            fattyAcidsMonounsaturated: 4.1,
            fattyAcidsPolyunsaturated: 1.4,
            chloride: 110.0
        }
    },
    {
        id: 6,
        name: "Milk (whole)",
        macronutrients: {
            energy: 61,
            carbohydrate: 4.8,
            fat: 3.2,
            protein: 3.2
        },
        micronutrients: {
            cholesterol: 10.0,
            fiber: null,
            sodium: 43.0,
            water: 88.0,
            vitaminA: 46.0,
            vitaminB6: 0.04,
            vitaminB12: 0.4,
            vitaminC: 0.0,
            vitaminD: 1.0,
            vitaminE: 0.1,
            vitaminK: 0.3,
            starch: 0.0,
            lactose: 4.8,
            alcohol: null,
            caffeine: null,
            sugars: 4.8,
            calcium: 113.0,
            iron: 0.0,
            magnesium: 10.0,
            phosphorus: 84.0,
            potassium: 132.0,
            zinc: 0.4,
            copper: 0.01,
            fluoride: null,
            manganese: 0.01,
            selenium: 1.0,
            thiamin: 0.04,
            riboflavin: 0.2,
            niacin: 0.1,
            pantothenicAcid: 0.4,
            folateTotal: 5.0,
            folicAcid: null,
            fattyAcidsTrans: 0.1,
            fattyAcidsSaturated: 1.9,
            fattyAcidsMonounsaturated: 0.8,
            fattyAcidsPolyunsaturated: 0.2,
            chloride: 105.0
        }
    },
    {
        id: 7,
        name: "Beef (lean, cooked)",
        macronutrients: {
            energy: 250,
            carbohydrate: 0.0,
            fat: 15.0,
            protein: 26.0
        },
        micronutrients: {
            cholesterol: 90.0,
            fiber: null,
            sodium: 72.0,
            water: 58.0,
            vitaminA: 0.0,
            vitaminB6: 0.4,
            vitaminB12: 2.6,
            vitaminC: 0.0,
            vitaminD: 0.0,
            vitaminE: 0.2,
            vitaminK: 1.3,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.0,
            calcium: 18.0,
            iron: 2.6,
            magnesium: 21.0,
            phosphorus: 180.0,
            potassium: 318.0,
            zinc: 5.1,
            copper: 0.09,
            fluoride: null,
            manganese: 0.01,
            selenium: 33.0,
            thiamin: 0.05,
            riboflavin: 0.2,
            niacin: 4.0,
            pantothenicAcid: 0.5,
            folateTotal: 9.0,
            folicAcid: null,
            fattyAcidsTrans: 0.5,
            fattyAcidsSaturated: 6.0,
            fattyAcidsMonounsaturated: 7.0,
            fattyAcidsPolyunsaturated: 0.5,
            chloride: 60.0
        }
    },
    {
        id: 8,
        name: "Salmon (grilled)",
        macronutrients: {
            energy: 206,
            carbohydrate: 0.0,
            fat: 12.0,
            protein: 22.0
        },
        micronutrients: {
            cholesterol: 63.0,
            fiber: null,
            sodium: 59.0,
            water: 64.0,
            vitaminA: 40.0,
            vitaminB6: 0.6,
            vitaminB12: 3.2,
            vitaminC: 0.0,
            vitaminD: 10.9,
            vitaminE: 1.1,
            vitaminK: 0.5,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.0,
            calcium: 9.0,
            iron: 0.5,
            magnesium: 27.0,
            phosphorus: 252.0,
            potassium: 384.0,
            zinc: 0.6,
            copper: 0.03,
            fluoride: null,
            manganese: 0.01,
            selenium: 36.5,
            thiamin: 0.1,
            riboflavin: 0.1,
            niacin: 8.0,
            pantothenicAcid: 1.0,
            folateTotal: 25.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 2.5,
            fattyAcidsMonounsaturated: 4.5,
            fattyAcidsPolyunsaturated: 3.8,
            chloride: 70.0
        }
    },
    {
        id: 9,
        name: "Tomato (raw)",
        macronutrients: {
            energy: 18,
            carbohydrate: 3.9,
            fat: 0.2,
            protein: 0.9
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 1.2,
            sodium: 5.0,
            water: 94.5,
            vitaminA: 833.0,
            vitaminB6: 0.08,
            vitaminB12: 0.0,
            vitaminC: 13.7,
            vitaminD: 0.0,
            vitaminE: 0.5,
            vitaminK: 7.9,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 2.6,
            calcium: 10.0,
            iron: 0.3,
            magnesium: 11.0,
            phosphorus: 24.0,
            potassium: 237.0,
            zinc: 0.2,
            copper: 0.06,
            fluoride: null,
            manganese: 0.1,
            selenium: 0.5,
            thiamin: 0.04,
            riboflavin: 0.02,
            niacin: 0.6,
            pantothenicAcid: 0.1,
            folateTotal: 15.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.03,
            fattyAcidsMonounsaturated: 0.03,
            fattyAcidsPolyunsaturated: 0.08,
            chloride: 8.0
        }
    },
    {
        id: 10,
        name: "Tofu (firm)",
        macronutrients: {
            energy: 144,
            carbohydrate: 3.9,
            fat: 8.0,
            protein: 15.0
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 0.3,
            sodium: 9.0,
            water: 72.0,
            vitaminA: 85.0,
            vitaminB6: 0.1,
            vitaminB12: 0.0,
            vitaminC: 0.1,
            vitaminD: 0.0,
            vitaminE: 0.1,
            vitaminK: 2.4,
            starch: 0.2,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.6,
            calcium: 350.0,
            iron: 2.7,
            magnesium: 30.0,
            phosphorus: 121.0,
            potassium: 148.0,
            zinc: 1.0,
            copper: 0.2,
            fluoride: null,
            manganese: 0.5,
            selenium: 17.4,
            thiamin: 0.1,
            riboflavin: 0.1,
            niacin: 0.5,
            pantothenicAcid: 0.2,
            folateTotal: 15.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 1.0,
            fattyAcidsMonounsaturated: 2.0,
            fattyAcidsPolyunsaturated: 4.0,
            chloride: 20.0
        }
    }, {
        id: 11,
        name: "Brown Rice (cooked)",
        macronutrients: {
            energy: 123,
            carbohydrate: 25.6,
            fat: 1.0,
            protein: 2.7
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 1.8,
            sodium: 4.0,
            water: 72.0,
            vitaminA: 0.0,
            vitaminB6: 0.14,
            vitaminB12: 0.0,
            vitaminC: 0.0,
            vitaminD: 0.0,
            vitaminE: 0.1,
            vitaminK: 0.6,
            starch: 23.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.2,
            calcium: 10.0,
            iron: 0.6,
            magnesium: 44.0,
            phosphorus: 83.0,
            potassium: 86.0,
            zinc: 0.9,
            copper: 0.1,
            fluoride: null,
            manganese: 1.1,
            selenium: 9.8,
            thiamin: 0.17,
            riboflavin: 0.02,
            niacin: 1.5,
            pantothenicAcid: 0.3,
            folateTotal: 4.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.2,
            fattyAcidsMonounsaturated: 0.3,
            fattyAcidsPolyunsaturated: 0.4,
            chloride: 7.0
        }
    },
    {
        id: 12,
        name: "Spinach (raw)",
        macronutrients: {
            energy: 23,
            carbohydrate: 3.6,
            fat: 0.4,
            protein: 2.9
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 2.2,
            sodium: 79.0,
            water: 91.4,
            vitaminA: 9377.0,
            vitaminB6: 0.2,
            vitaminB12: 0.0,
            vitaminC: 28.0,
            vitaminD: 0.0,
            vitaminE: 2.0,
            vitaminK: 482.9,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.4,
            calcium: 99.0,
            iron: 2.7,
            magnesium: 79.0,
            phosphorus: 49.0,
            potassium: 558.0,
            zinc: 0.5,
            copper: 0.13,
            fluoride: null,
            manganese: 0.9,
            selenium: 1.0,
            thiamin: 0.08,
            riboflavin: 0.19,
            niacin: 0.7,
            pantothenicAcid: 0.1,
            folateTotal: 194.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 0.06,
            fattyAcidsMonounsaturated: 0.01,
            fattyAcidsPolyunsaturated: 0.17,
            chloride: 50.0
        }
    },
    {
        id: 13,
        name: "Almonds (raw)",
        macronutrients: {
            energy: 579,
            carbohydrate: 21.6,
            fat: 49.9,
            protein: 21.2
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 12.5,
            sodium: 1.0,
            water: 4.4,
            vitaminA: 1.0,
            vitaminB6: 0.14,
            vitaminB12: 0.0,
            vitaminC: 0.0,
            vitaminD: 0.0,
            vitaminE: 25.6,
            vitaminK: 0.0,
            starch: 0.0,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 4.4,
            calcium: 269.0,
            iron: 3.7,
            magnesium: 270.0,
            phosphorus: 481.0,
            potassium: 733.0,
            zinc: 3.1,
            copper: 1.0,
            fluoride: null,
            manganese: 2.3,
            selenium: 2.5,
            thiamin: 0.2,
            riboflavin: 1.1,
            niacin: 3.6,
            pantothenicAcid: 0.5,
            folateTotal: 60.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 3.7,
            fattyAcidsMonounsaturated: 31.6,
            fattyAcidsPolyunsaturated: 12.3,
            chloride: 100.0
        }
    },
    {
        id: 14,
        name: "Avocado (raw)",
        macronutrients: {
            energy: 160,
            carbohydrate: 8.5,
            fat: 14.7,
            protein: 2.0
        },
        micronutrients: {
            cholesterol: 0.0,
            fiber: 6.7,
            sodium: 7.0,
            water: 73.2,
            vitaminA: 146.0,
            vitaminB6: 0.3,
            vitaminB12: 0.0,
            vitaminC: 10.0,
            vitaminD: 0.0,
            vitaminE: 2.1,
            vitaminK: 21.0,
            starch: 0.1,
            lactose: 0.0,
            alcohol: null,
            caffeine: null,
            sugars: 0.7,
            calcium: 12.0,
            iron: 0.6,
            magnesium: 29.0,
            phosphorus: 52.0,
            potassium: 485.0,
            zinc: 0.6,
            copper: 0.2,
            fluoride: null,
            manganese: 0.1,
            selenium: 0.4,
            thiamin: 0.07,
            riboflavin: 0.13,
            niacin: 1.7,
            pantothenicAcid: 1.4,
            folateTotal: 81.0,
            folicAcid: null,
            fattyAcidsTrans: 0.0,
            fattyAcidsSaturated: 2.1,
            fattyAcidsMonounsaturated: 9.8,
            fattyAcidsPolyunsaturated: 1.8,
            chloride: 20.0
        }
    }
];

if (!localStorage.getItem("ingredients")) {
    const ingredients = [
        {
            id: 1,
            name: "Broccoli",
            macronutrients: {
                energy: 34,
                carbohydrate: 6.6,
                fat: 0.4,
                protein: 2.8
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 2.6,
                sodium: 33.0,
                water: 89.3,
                vitaminA: 623.0,
                vitaminB6: 0.2,
                vitaminB12: 0.0,
                vitaminC: 89.2,
                vitaminD: 0.0,
                vitaminE: 0.8,
                vitaminK: 101.6,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 1.7,
                calcium: 47.0,
                iron: 0.7,
                magnesium: 21.0,
                phosphorus: 66.0,
                potassium: 316.0,
                zinc: 0.4,
                copper: 0.05,
                fluoride: null,
                manganese: 0.2,
                selenium: 2.5,
                thiamin: 0.07,
                riboflavin: 0.12,
                niacin: 0.64,
                pantothenicAcid: 0.5,
                folateTotal: 63.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.04,
                fattyAcidsMonounsaturated: 0.01,
                fattyAcidsPolyunsaturated: 0.04,
                chloride: 55.0
            }
        },
        {
            id: 2,
            name: "Chicken Breast",
            macronutrients: {
                energy: 165,
                carbohydrate: 0.0,
                fat: 3.6,
                protein: 31.0
            },
            micronutrients: {
                cholesterol: 85.0,
                fiber: null,
                sodium: 74.0,
                water: 65.3,
                vitaminA: 13.0,
                vitaminB6: 0.6,
                vitaminB12: 0.3,
                vitaminC: 0.0,
                vitaminD: 0.1,
                vitaminE: 0.27,
                vitaminK: 0.3,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.0,
                calcium: 15.0,
                iron: 1.0,
                magnesium: 29.0,
                phosphorus: 220.0,
                potassium: 256.0,
                zinc: 1.0,
                copper: 0.04,
                fluoride: null,
                manganese: 0.02,
                selenium: 27.6,
                thiamin: 0.07,
                riboflavin: 0.1,
                niacin: 13.7,
                pantothenicAcid: 1.0,
                folateTotal: 4.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 1.0,
                fattyAcidsMonounsaturated: 1.2,
                fattyAcidsPolyunsaturated: 0.8,
                chloride: 60.0
            }
        },
        {
            id: 3,
            name: "White Rice (cooked)",
            macronutrients: {
                energy: 130,
                carbohydrate: 28.0,
                fat: 0.3,
                protein: 2.7
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 0.4,
                sodium: 1.0,
                water: 68.4,
                vitaminA: null,
                vitaminB6: 0.1,
                vitaminB12: 0.0,
                vitaminC: 0.0,
                vitaminD: 0.0,
                vitaminE: 0.1,
                vitaminK: 0.1,
                starch: 26.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.1,
                calcium: 10.0,
                iron: 1.2,
                magnesium: 12.0,
                phosphorus: 43.0,
                potassium: 35.0,
                zinc: 0.4,
                copper: 0.07,
                fluoride: null,
                manganese: 0.5,
                selenium: 7.5,
                thiamin: 0.02,
                riboflavin: 0.02,
                niacin: 0.4,
                pantothenicAcid: 0.4,
                folateTotal: 58.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.1,
                fattyAcidsMonounsaturated: 0.1,
                fattyAcidsPolyunsaturated: 0.1,
                chloride: 1.0
            }
        }, {
            id: 4,
            name: "Banana",
            macronutrients: {
                energy: 89,
                carbohydrate: 22.8,
                fat: 0.3,
                protein: 1.1
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 2.6,
                sodium: 1.0,
                water: 74.9,
                vitaminA: 64.0,
                vitaminB6: 0.4,
                vitaminB12: 0.0,
                vitaminC: 8.7,
                vitaminD: 0.0,
                vitaminE: 0.1,
                vitaminK: 0.5,
                starch: 5.4,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 12.2,
                calcium: 5.0,
                iron: 0.3,
                magnesium: 27.0,
                phosphorus: 22.0,
                potassium: 358.0,
                zinc: 0.2,
                copper: 0.08,
                fluoride: null,
                manganese: 0.3,
                selenium: 1.0,
                thiamin: 0.03,
                riboflavin: 0.07,
                niacin: 0.7,
                pantothenicAcid: 0.3,
                folateTotal: 20.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.1,
                fattyAcidsMonounsaturated: 0.03,
                fattyAcidsPolyunsaturated: 0.07,
                chloride: 3.0
            }
        },
        {
            id: 5,
            name: "Egg (boiled)",
            macronutrients: {
                energy: 155,
                carbohydrate: 1.1,
                fat: 11.0,
                protein: 13.0
            },
            micronutrients: {
                cholesterol: 373.0,
                fiber: null,
                sodium: 124.0,
                water: 75.0,
                vitaminA: 160.0,
                vitaminB6: 0.1,
                vitaminB12: 1.1,
                vitaminC: 0.0,
                vitaminD: 2.0,
                vitaminE: 1.0,
                vitaminK: 0.3,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 1.1,
                calcium: 50.0,
                iron: 1.2,
                magnesium: 10.0,
                phosphorus: 86.0,
                potassium: 126.0,
                zinc: 1.0,
                copper: 0.06,
                fluoride: null,
                manganese: 0.03,
                selenium: 30.8,
                thiamin: 0.03,
                riboflavin: 0.5,
                niacin: 0.1,
                pantothenicAcid: 1.4,
                folateTotal: 47.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 3.3,
                fattyAcidsMonounsaturated: 4.1,
                fattyAcidsPolyunsaturated: 1.4,
                chloride: 110.0
            }
        },
        {
            id: 6,
            name: "Milk (whole)",
            macronutrients: {
                energy: 61,
                carbohydrate: 4.8,
                fat: 3.2,
                protein: 3.2
            },
            micronutrients: {
                cholesterol: 10.0,
                fiber: null,
                sodium: 43.0,
                water: 88.0,
                vitaminA: 46.0,
                vitaminB6: 0.04,
                vitaminB12: 0.4,
                vitaminC: 0.0,
                vitaminD: 1.0,
                vitaminE: 0.1,
                vitaminK: 0.3,
                starch: 0.0,
                lactose: 4.8,
                alcohol: null,
                caffeine: null,
                sugars: 4.8,
                calcium: 113.0,
                iron: 0.0,
                magnesium: 10.0,
                phosphorus: 84.0,
                potassium: 132.0,
                zinc: 0.4,
                copper: 0.01,
                fluoride: null,
                manganese: 0.01,
                selenium: 1.0,
                thiamin: 0.04,
                riboflavin: 0.2,
                niacin: 0.1,
                pantothenicAcid: 0.4,
                folateTotal: 5.0,
                folicAcid: null,
                fattyAcidsTrans: 0.1,
                fattyAcidsSaturated: 1.9,
                fattyAcidsMonounsaturated: 0.8,
                fattyAcidsPolyunsaturated: 0.2,
                chloride: 105.0
            }
        },
        {
            id: 7,
            name: "Beef (lean, cooked)",
            macronutrients: {
                energy: 250,
                carbohydrate: 0.0,
                fat: 15.0,
                protein: 26.0
            },
            micronutrients: {
                cholesterol: 90.0,
                fiber: null,
                sodium: 72.0,
                water: 58.0,
                vitaminA: 0.0,
                vitaminB6: 0.4,
                vitaminB12: 2.6,
                vitaminC: 0.0,
                vitaminD: 0.0,
                vitaminE: 0.2,
                vitaminK: 1.3,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.0,
                calcium: 18.0,
                iron: 2.6,
                magnesium: 21.0,
                phosphorus: 180.0,
                potassium: 318.0,
                zinc: 5.1,
                copper: 0.09,
                fluoride: null,
                manganese: 0.01,
                selenium: 33.0,
                thiamin: 0.05,
                riboflavin: 0.2,
                niacin: 4.0,
                pantothenicAcid: 0.5,
                folateTotal: 9.0,
                folicAcid: null,
                fattyAcidsTrans: 0.5,
                fattyAcidsSaturated: 6.0,
                fattyAcidsMonounsaturated: 7.0,
                fattyAcidsPolyunsaturated: 0.5,
                chloride: 60.0
            }
        },
        {
            id: 8,
            name: "Salmon (grilled)",
            macronutrients: {
                energy: 206,
                carbohydrate: 0.0,
                fat: 12.0,
                protein: 22.0
            },
            micronutrients: {
                cholesterol: 63.0,
                fiber: null,
                sodium: 59.0,
                water: 64.0,
                vitaminA: 40.0,
                vitaminB6: 0.6,
                vitaminB12: 3.2,
                vitaminC: 0.0,
                vitaminD: 10.9,
                vitaminE: 1.1,
                vitaminK: 0.5,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.0,
                calcium: 9.0,
                iron: 0.5,
                magnesium: 27.0,
                phosphorus: 252.0,
                potassium: 384.0,
                zinc: 0.6,
                copper: 0.03,
                fluoride: null,
                manganese: 0.01,
                selenium: 36.5,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 8.0,
                pantothenicAcid: 1.0,
                folateTotal: 25.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 2.5,
                fattyAcidsMonounsaturated: 4.5,
                fattyAcidsPolyunsaturated: 3.8,
                chloride: 70.0
            }
        },
        {
            id: 9,
            name: "Tomato (raw)",
            macronutrients: {
                energy: 18,
                carbohydrate: 3.9,
                fat: 0.2,
                protein: 0.9
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 1.2,
                sodium: 5.0,
                water: 94.5,
                vitaminA: 833.0,
                vitaminB6: 0.08,
                vitaminB12: 0.0,
                vitaminC: 13.7,
                vitaminD: 0.0,
                vitaminE: 0.5,
                vitaminK: 7.9,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 2.6,
                calcium: 10.0,
                iron: 0.3,
                magnesium: 11.0,
                phosphorus: 24.0,
                potassium: 237.0,
                zinc: 0.2,
                copper: 0.06,
                fluoride: null,
                manganese: 0.1,
                selenium: 0.5,
                thiamin: 0.04,
                riboflavin: 0.02,
                niacin: 0.6,
                pantothenicAcid: 0.1,
                folateTotal: 15.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.03,
                fattyAcidsMonounsaturated: 0.03,
                fattyAcidsPolyunsaturated: 0.08,
                chloride: 8.0
            }
        },
        {
            id: 10,
            name: "Tofu (firm)",
            macronutrients: {
                energy: 144,
                carbohydrate: 3.9,
                fat: 8.0,
                protein: 15.0
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 0.3,
                sodium: 9.0,
                water: 72.0,
                vitaminA: 85.0,
                vitaminB6: 0.1,
                vitaminB12: 0.0,
                vitaminC: 0.1,
                vitaminD: 0.0,
                vitaminE: 0.1,
                vitaminK: 2.4,
                starch: 0.2,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.6,
                calcium: 350.0,
                iron: 2.7,
                magnesium: 30.0,
                phosphorus: 121.0,
                potassium: 148.0,
                zinc: 1.0,
                copper: 0.2,
                fluoride: null,
                manganese: 0.5,
                selenium: 17.4,
                thiamin: 0.1,
                riboflavin: 0.1,
                niacin: 0.5,
                pantothenicAcid: 0.2,
                folateTotal: 15.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 1.0,
                fattyAcidsMonounsaturated: 2.0,
                fattyAcidsPolyunsaturated: 4.0,
                chloride: 20.0
            }
        }, {
            id: 11,
            name: "Brown Rice (cooked)",
            macronutrients: {
                energy: 123,
                carbohydrate: 25.6,
                fat: 1.0,
                protein: 2.7
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 1.8,
                sodium: 4.0,
                water: 72.0,
                vitaminA: 0.0,
                vitaminB6: 0.14,
                vitaminB12: 0.0,
                vitaminC: 0.0,
                vitaminD: 0.0,
                vitaminE: 0.1,
                vitaminK: 0.6,
                starch: 23.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.2,
                calcium: 10.0,
                iron: 0.6,
                magnesium: 44.0,
                phosphorus: 83.0,
                potassium: 86.0,
                zinc: 0.9,
                copper: 0.1,
                fluoride: null,
                manganese: 1.1,
                selenium: 9.8,
                thiamin: 0.17,
                riboflavin: 0.02,
                niacin: 1.5,
                pantothenicAcid: 0.3,
                folateTotal: 4.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.2,
                fattyAcidsMonounsaturated: 0.3,
                fattyAcidsPolyunsaturated: 0.4,
                chloride: 7.0
            }
        },
        {
            id: 12,
            name: "Spinach (raw)",
            macronutrients: {
                energy: 23,
                carbohydrate: 3.6,
                fat: 0.4,
                protein: 2.9
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 2.2,
                sodium: 79.0,
                water: 91.4,
                vitaminA: 9377.0,
                vitaminB6: 0.2,
                vitaminB12: 0.0,
                vitaminC: 28.0,
                vitaminD: 0.0,
                vitaminE: 2.0,
                vitaminK: 482.9,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.4,
                calcium: 99.0,
                iron: 2.7,
                magnesium: 79.0,
                phosphorus: 49.0,
                potassium: 558.0,
                zinc: 0.5,
                copper: 0.13,
                fluoride: null,
                manganese: 0.9,
                selenium: 1.0,
                thiamin: 0.08,
                riboflavin: 0.19,
                niacin: 0.7,
                pantothenicAcid: 0.1,
                folateTotal: 194.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 0.06,
                fattyAcidsMonounsaturated: 0.01,
                fattyAcidsPolyunsaturated: 0.17,
                chloride: 50.0
            }
        },
        {
            id: 13,
            name: "Almonds (raw)",
            macronutrients: {
                energy: 579,
                carbohydrate: 21.6,
                fat: 49.9,
                protein: 21.2
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 12.5,
                sodium: 1.0,
                water: 4.4,
                vitaminA: 1.0,
                vitaminB6: 0.14,
                vitaminB12: 0.0,
                vitaminC: 0.0,
                vitaminD: 0.0,
                vitaminE: 25.6,
                vitaminK: 0.0,
                starch: 0.0,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 4.4,
                calcium: 269.0,
                iron: 3.7,
                magnesium: 270.0,
                phosphorus: 481.0,
                potassium: 733.0,
                zinc: 3.1,
                copper: 1.0,
                fluoride: null,
                manganese: 2.3,
                selenium: 2.5,
                thiamin: 0.2,
                riboflavin: 1.1,
                niacin: 3.6,
                pantothenicAcid: 0.5,
                folateTotal: 60.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 3.7,
                fattyAcidsMonounsaturated: 31.6,
                fattyAcidsPolyunsaturated: 12.3,
                chloride: 100.0
            }
        },
        {
            id: 14,
            name: "Avocado (raw)",
            macronutrients: {
                energy: 160,
                carbohydrate: 8.5,
                fat: 14.7,
                protein: 2.0
            },
            micronutrients: {
                cholesterol: 0.0,
                fiber: 6.7,
                sodium: 7.0,
                water: 73.2,
                vitaminA: 146.0,
                vitaminB6: 0.3,
                vitaminB12: 0.0,
                vitaminC: 10.0,
                vitaminD: 0.0,
                vitaminE: 2.1,
                vitaminK: 21.0,
                starch: 0.1,
                lactose: 0.0,
                alcohol: null,
                caffeine: null,
                sugars: 0.7,
                calcium: 12.0,
                iron: 0.6,
                magnesium: 29.0,
                phosphorus: 52.0,
                potassium: 485.0,
                zinc: 0.6,
                copper: 0.2,
                fluoride: null,
                manganese: 0.1,
                selenium: 0.4,
                thiamin: 0.07,
                riboflavin: 0.13,
                niacin: 1.7,
                pantothenicAcid: 1.4,
                folateTotal: 81.0,
                folicAcid: null,
                fattyAcidsTrans: 0.0,
                fattyAcidsSaturated: 2.1,
                fattyAcidsMonounsaturated: 9.8,
                fattyAcidsPolyunsaturated: 1.8,
                chloride: 20.0
            }
        }
    ];
    localStorage.setItem("ingredients", JSON.stringify(ingredients));
    window.ingredients = ingredients;
    console.log("✅ Đã lưu ingredients vào localStorage.");
} else {
    window.ingredients = JSON.parse(localStorage.getItem("ingredients"));
    console.log("✅ Đã lấy ingredients từ localStorage.");
}

